"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
const links = [["/#inicio","Inicio"],["/#quienes-somos","Quiénes somos"],["/#donde-estamos","Dónde estamos"],["/#nuestra-agua","Nuestra agua"],["/#productos","Productos"],["/#reconocimientos","Reconocimientos"],["/#franquicias","Franquicias"],["/contacto","Contacto"],["/#redes","Redes"]];
export function Navbar() {
  const [isOpen,setIsOpen]=useState(false);
  const pathname=usePathname();
  return <header className="sticky top-0 z-50 border-b border-slate-100 bg-white/95 backdrop-blur"><nav aria-label="Navegación principal" className="page-container flex h-20 items-center justify-between lg:h-24"><Link href="/#inicio" aria-label="OMI, ir al inicio"><Image src="/images/brand/omi-logo.png" alt="" width={1962} height={802} priority sizes="112px" className="h-10 w-auto object-contain lg:h-12" /></Link><ul className="hidden items-center gap-5 text-[13px] font-medium text-[#061643] xl:flex">{links.map(([href,label],i)=>{const active=href==="/contacto"?pathname==="/contacto":i===0&&pathname==="/";return <li key={href}><Link href={href} aria-current={active?"page":undefined} className={`nav-link ${active?"active":""}`}>{label}</Link></li>})}</ul><div className="relative xl:hidden"><button type="button" aria-expanded={isOpen} aria-controls="mobile-navigation" aria-label={isOpen?"Cerrar menú":"Abrir menú"} onClick={()=>setIsOpen(open=>!open)} className="grid size-11 place-items-center rounded-full border border-blue-200 text-[#061643] hover:bg-blue-50 focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-4 focus-visible:outline-[#58aceb]"><span className="text-2xl" aria-hidden="true">{isOpen?"×":"☰"}</span></button>{isOpen&&<div id="mobile-navigation" className="absolute right-0 top-14 max-h-[calc(100vh-6rem)] w-72 overflow-y-auto rounded-2xl border border-blue-100 bg-white p-2 shadow-xl">{links.map(([href,label])=><Link key={href} href={href} onClick={()=>setIsOpen(false)} className="block rounded-xl px-4 py-2.5 text-sm font-medium text-[#061643] hover:bg-blue-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[#58aceb]">{label}</Link>)}</div>}</div></nav></header>;
}
